version: "3.4"
services:
  configservice:
    image: chenchuxin/apollo
    environment:
      - spring_datasource_url=jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=root
      - logging.file=/opt/logs/configservice.log
      - server.port=8080
    volumes:
      - /var/log/apollo:/opt/logs
    command: configservice.jar
    links:
      - mysql:mysql
    networks: 
      - dev
    restart: always

  adminservice:
    image: chenchuxin/apollo
    environment:
      - spring_datasource_url=jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=root
      - logging.file=/opt/logs/adminservice.log
      - server.port=8090
    volumes:
      - /var/log/apollo:/opt/logs
    command: adminservice.jar
    links:
      - mysql:mysql
    networks: 
      - dev
    depends_on:
      - configservice
    restart: always

  portal:
    image: chenchuxin/apollo
    environment:
      - spring_datasource_url=jdbc:mysql://mysql:3306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=root
      - server.port=8070
      - logging.file=/opt/logs/portal.log
    volumes:
      - /var/log/apollo:/opt/logs
    command: -Ddev_meta=http://localhost:8080 portal.jar
    links:
      - mysql:mysql
    networks: 
      - dev
    depends_on:
      - adminservice
    restart: always
