version: '2.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/docker-healthcheck:/usr/local/bin/docker-healthcheck
    healthcheck:
      test: "docker-healthcheck"
    networks:
      apollonet:
        aliases:
          - db.local

  apollo:
    image: logzio/apollo:latest
    ports:
      - "8081:8081"
      - "30001:80"
    restart: always
    environment:
      APOLLO_CONFIG_FILEPATH: /root/apollo.conf
    volumes:
      - ./apollo.conf:/root/apollo.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      db:
        condition: service_healthy
    networks:
      apollonet:
        aliases:
          - apollo.local

networks:
  apollonet: